spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/Citronnix
    username: postgres
    password: Administrateur
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate.format_sql: true
  logging:
    level:
      org.hibernate.SQL: DEBUG
      org.hibernate.type.descriptor.sql: trace
